AllCops:
  Exclude:
  - 'lib/lecter/html_generator.rb'
  - 'lib/lecter/rack.rb'
  - 'lib/lecter/trace_point.rb'
  - 'vendor/**/*'
Documentation:
  Enabled: false
Layout/LineLength:
  Max: 100
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2
