version: 2
references:
  rspec: &rspec
    run:
      name: Run test suite
      command: |
        ./tmp/cc-test-reporter before-build
        COVERAGE=true bundle exec rake spec
        ./tmp/cc-test-reporter format-coverage --output tmp/codeclimate.$CIRCLE_JOB.json
  rubocop: &rubocop
    run:
      name: Run rubocop linter
      command: bundle exec rubocop
  restore: &restore
    restore_cache:
      keys:
      - v1-dependencies-{{ checksum "Gemfile.lock" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-
  bundle: &bundle
    run:
      name: install dependencies
      command: |
        gem install bundler -v 2.1.2
        bundle install --path vendor/bundle
  save: &save
    save_cache:
      paths:
      - ./vendor/bundle
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  code-coverage: &code-coverage
    run:
      name: Setup Code Climate test-reporter
      command: |
        # download test reporter as a static binary
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
jobs:
  "all-in-one":
    environment:
      CC_TEST_REPORTER_ID: 4417938970048334f96d30fbe72a28c2ded3027bdf23f05a0cf06a50807a7873
    docker:
    - image: circleci/ruby:2.6.3
    steps:
    - checkout
    - <<: *restore
    - <<: *bundle
    - <<: *save
    - <<: *rspec
    - <<: *rubocop
    - <<: *code-coverage

workflows:
  version: 2
  build:
    jobs:
    - 'all-in-one'