version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    executor: ruby
    steps:
    - checkout
    - resolve-dependencies
    - run-linter
  build-rspec:
    executor: ruby
    steps:
    - checkout
    - resolve-dependencies
    - run-linter
    - run-tests-rspec
  run-linter:
    steps:
    - run:
        name: Run Rubocop verifications
        command: |
          mkdir -p /tmp/linter-results/rubocop
          bundle exec rubocop \
            --require rubocop/formatter/junit_formatter \
            --format RuboCop::Formatter::JUnitFormatter \
            --out /tmp/linter-results/rubocop/results.xml
    - store_test_results:
        path: /tmp/linter-results