version: 2.1
references:
  rspec: &rspec
    run:
      name: Run test suite
      command: bundle exec rspec
  restore: &restore
    restore_cache:
      keys:
      - v1-dependencies-{{ checksum "Gemfile.lock" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-
  bundle: &bundle
    run:
      name: install dependencies
      command: bundle install --path vendor/bundle
  save: &save
    save_cache:
      paths:
      - ./vendor/bundle
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}
jobs:
  "ruby-2.5":
    docker:
    - image: circleci/ruby:2.6.3
    steps:
    - checkout
    - <<: *restore
    - <<: *bundle
    - <<: *save
    - <<: *rspec

workflows:
  version: 2
  build:
    jobs:
    - "ruby-2.6.3"
