version: 2
references:
  rspec: &rspec
    run:
      name: Run test suite
      command: bundle exec rspec
  rubocop: &rubocop
    run:
      name: Run rubocop linter
      command: bundle exec rubocop
  restore: &restore
    restore_cache:
      keys:
      - v1-dependencies-{{ checksum "Gemfile.lock" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-
  bundle: &bundle
    run:
      name: install dependencies
      command: |
        gem install bundler -v 2.1.2
        bundle install --path vendor/bundle
  save: &save
    save_cache:
      paths:
      - ./vendor/bundle
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  send_coverage_report: &send_coverage_report
    - coverage-reporter/send_report
jobs:
  "ruby-2.6.3":
    docker:
    - image: circleci/ruby:2.6.3
    steps:
    - checkout
    - <<: *restore
    - <<: *bundle
    - <<: *save
    - <<: *rspec
    - <<: *rubocop
    - <<: *send_coverage_report

workflows:
  version: 2
  build:
    jobs:
    - "ruby-2.6.3"
